### ISSUE TITLE
Use contextualized localisation files

### ISSUE THREAD

**Issue by m4dz** [cozy/cozy-guidelines#12]
Since v0.4.0, Polyglot supports [nested phrase objects](http://airbnb.github.io/polyglot.js/#interpolation). I suggest we use it to contextualize our localisation files, as it may simplifies future changes to this files. I also recommend (if we stick to my suggestion) to sandbox contexts in separated files, to keep them more consistent.

Here's a little example:

In home, we,ve got many contexts, such as app store, settings, wizards, etc. We could have a file tree like this:

```
client
    `- app
        `- locales
            |- en
            `- fr
                |- locale.coffee             # the main file to import
                |- app_store.coffee          # app store contextualized phrases
                |- install_wizard.coffee
                `- quicktour_wizard.coffee
```

Then each context file declares its phrases as usual:
```coffee
module.exports =
    'hello': "Hello World"
```
and the main file `locale.coffee` import them in nested contexts:
```coffee
module.exports = 
    'home':             "Home"
    'app_store':        require './app_store'
    'install_wizard':   require './install_wizard'
    'quicktour_wizard': require './quicktour_wizard'
```

Then, we load the main locale with polyglot:
```coffee
@polyglot = new Polyglot()
@polyglot.extend require "locales/#{@locale}/locale"
```
and use nested phrases as context:
```jade
h1= t('app_store.hello')
```

**Comment by frankrousseau** [comment]
The idea is nice, but it brings complexity. I propose to not follow it for the moment.
