### ISSUE TITLE
Move this repository to Github pages

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-guidelines#23]

**Comment by frankrousseau** [comment]
What do you mean by moving the repository?

**Comment by clochix** [comment]
Not really moving, just create a gh-page branch, make it the default branch and delete master branch.

**Comment by frankrousseau** [comment]
ok.

**Comment by clochix** [comment]
Done: http://cozy.github.io/cozy-guidelines/
To update this site when the README is updated, just go to project settings, “Launch automatic page generator”, then click on “Load README”.
Pinging @jsilvestre.

**Comment by frankrousseau** [comment]
Like Frenches say: "Cébo"
