### ISSUE TITLE
How we should write mocha tests

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-guidelines#3]
Guidelines don't talk much about tests. I think we could add one thing and discuss another one.

1. We can consider as a guideline that Mocha is the framework to use for server side tests. We can discuss about that, but I think every one will agree.

2. We should decide on a way to write tests. I think we have a lot of different way to do in our projects and that makes thing messy. If we could agree on how do things (and maybe build a framework on top of mocha to manage it) that could be great.

**Comment by jsilvestre** [comment]
3. How to test, what to mock, and what not to mock; when to do integration tests.

**Comment by aenario** [comment]
- use mocha
- use should (and not chai / expect)
- use latest mocha scoping rules (otherwise, incompatibilities between mocha versions)
- use cozy-fixtures
- test JS build on travis
- always clean before & after each tests file (otherwise we cant run them separately)

To be discussed
- avoid setTimeout to wait for async results (hooks / spy)
- there is an artistic blur with the order of : startApp, cleandb, fixtures ?
- include lint in tests ?
- how to mock (mock, sinon, ...)

**Comment by aenario** [comment]
Not sure if we ought to wrap mocha, but I am +1 on a toolbelt which should include :

- proper startup & takedown (might be linked with americano app initialization)
- proper fixtures & cleaning

**Comment by jsilvestre** [comment]
> use latest mocha scoping rules (otherwise, incompatibilities between mocha versions)
We could use "./node_modules/.bin/mocha" to ensure mocha version

> use cozy-fixtures
Maybe we could add "improve cozy-fixtures", the remove process is very slow and sometimes fail when there are many docs.

> test JS build on travis
It's done in all the Cakefile I did (--use-js option). Or do you mean to test the build process itself somehow?

> avoid setTimeout to wait for async results (hooks / spy)
Yes, yes and yes. If the depends on setTimeout, we can use sinon.fakeTimers

> there is an artistic blur with the order of : startApp, cleandb, fixtures ?
I personally use "clean database, load fixtures, start app"

> include lint in tests ?
If we find a good combination, I'm all for it.

> how to mock (mock, sinon, ...)
I can definitely help with that (guide, talk). Sinon is very powerful!

**Comment by frankrousseau** [comment]
I propose that rules too:

* at least one file per module
* split big modules in several files
* split test file that runs in more than 1 minute

**Comment by jsilvestre** [comment]
> split test file that runs in more than 1 minute
I think splitting the test file is trying to keep the patient alive, rather than healing him. I think that most times, tests can be written differently. So I agree files should be split if the tests are too slow, but we should also look after the causes.

**Comment by frankrousseau** [comment]
So here are the complete guidelines. Feel free to improve it by submitting a PR:

* Use Mocha (install and run it via dependencies `./node_modules/mocha/bin`).
* Use should (and not chai / expect)
* Use latest mocha scoping rules (otherwise, incompatibilities between mocha versions)
* Use cozy-fixtures
* Use linter
* Run tests on JS build on travis
* Always clean before & after each tests file (otherwise we cant run them separately)
* Split big modules in several files
* Split test file that runs in more than 1 minute (and that are too complex to be made faster)
* For route testing, run operation in the following order : Clean DB, Add fixtures, Start application

**Comment by frankrousseau** [comment]
Here is the related [file](https://github.com/cozy/cozy-guidelines/blob/master/testing.md)
