### ISSUE TITLE
Standardization of git commit messages

### ISSUE THREAD

**Issue by enguerran** [cozy/cozy-guidelines#45]
A git repository lives with an history that let developers or automatic procedure to find useful information. Therefore a minimum of standardization is very valuable to every steps in a development/maintenance workflow.

Commits' messages are a part of development and commits' messages guidelines are part of development guidelines.

I found a very welldone commits's messages styleguide: https://udacity.github.io/git-styleguide/

If maintainers agree, I will add a Pull-Request to enhance the current styleguide with some kind of commits' messages styleguide inspired by udacity's one.

**Comment by drazik** [comment]
It seems udacity just follow https://conventionalcommits.org/, which is what we also decided to follow on cozy-ui (we even lint commit messages in it now : https://github.com/cozy/cozy-ui/pull/519).

I think it's a good idea to follow such widely adopted conventions :+1:

**Comment by enguerran** [comment]
We will need a PR titles styleguide and what strategy to insert PR's commits into the master branch, aka git workflow in order to have a useful git tree history.

**Comment by enguerran** [comment]
From this PR:
![image](https://user-images.githubusercontent.com/701648/41157341-bc4cb210-6b25-11e8-993e-db74ee49eb87.png)

# 1) full rebase

![image](https://user-images.githubusercontent.com/701648/41157424-fb7db3a8-6b25-11e8-88b4-40946280caeb.png)
