### ISSUE TITLE
Add an optional scope to git messages

### ISSUE THREAD

**Issue by drazik** [cozy/cozy-guidelines#49]
I think adding a scope is very informative in some commit messages. To use an example from our current guidelines, I think this commit message:

```
fix(contacts): A too long list breaks the scrolling
```

is way more informative than the version without the scope:

```
fix: A too long list breaks the scrolling
```

The fact that this refers to the contacts list can be written in the body, but I think that's not the place for such an information.

Also, this is a good help to write changelogs (manually or automatically). semantic-release uses it, for example.

Obviously, sometimes this scope doesn't add any information, so it must be optionnal.

See https://conventionalcommits.org/#spec-item-4 for more informations about the scope in the conventional commits specification, which widely inspired udacity.

What do you think about it ?

**Comment by ptbrowne** [comment]
Yes please.

**Comment by gregorylegarec** [comment]
I do not use scope in a regular basis but if some of us use to, let's add it to the guidelines.
