### ISSUE TITLE
REST responses

### ISSUE THREAD

**Issue by jsilvestre** [cozy/cozy-guidelines#6]
I noticed in controllers we do a lot of that to answer HTTP requests:
```coffeescript
# error case
res.send 500, error: true, msg: errorMessage

# success case
res.send success: true, data: "..."
```
The problem is that the "error" status should be handled through HTTP status code. I suggest we stop doing that and start changing it when we see it in our existing code. Instead, we can do:

```coffeescript
# error case
res.send 500, error: errorMessage

# success case
res.send 200, data: "..." # or just data
```
For the same (standardized) meaning.

What do you think?

**Comment by aenario** [comment]
+1 on success case
for error case, we should always 
```coffee
err = new Error 'shit happens'
err.status = 500
next err
```
The errorHandler middleware should be responsible to display JSON or html depending on client.

Writing these three lines everytime is a PITA, so it is cleaner to have helpers functions in an 'errors' file
```coffee
exports.NotFound = (what) ->
    err = new Error 'Not Found : ' + what
    err.status = 404
    return err
```
which can then be used as 

```coffee
if not someModel.someProperty
   next NotFound 'someModel.someProperty'
```

May be we should include these function in americano ?

**Comment by jsilvestre** [comment]
Yeah I didn't think about that, but I'm all for that kind of error management. Much, much cleaner. The point is the same though: using HTTP standard over our own convention.

**Comment by frankrousseau** [comment]
I think you mix two things here: HTTP conventions and what to put in the body of an error return.

What do you think about this guideline (I'm a little bit afraid that the second point of success response will lead to many changes in our code):

### Success response

* Always set the proper status (`200` for success, `201` for creation, `204` for deletion).
* Put the content of the answer in a data field.

### Error response

Always returned error with the proper status too by using the `next` function from Express:

```coffeescript
err = new Error 'Not Found : ' + what
err.status = 404
return err
```

**Comment by jsilvestre** [comment]
My example was a bit misleading: the "data" field is not what Backbone expects in return in case of success, if I remind correctly. By "data: ...", I meant just an object. If it's the data, go with the object itself.

Otherwise I agree.

**Comment by frankrousseau** [comment]
Thank you for the feedback. I fixed my previous comment and put it in the repository. Feel free to discuss it via a PR.

https://github.com/cozy/cozy-guidelines/commit/c297cad4145488dfdecac2c26df13f1bcae33625
